apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}
  labels:
    app: {{.Release.Name}}
spec:
  ingressClassName: nginx
  rules:
    - host: ""
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: {{.Release.Name}}
                port:
                  number: {{.Values.service.port}}
          - path: /default
            pathType: Prefix
            backend:
              service:
                name: {{.Release.Name}}
                port:
                  number: {{.Values.service.port}}
