apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Release.Name}}
  name: {{.Release.Name}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.service.port}}
      protocol: TCP
      targetPort: {{.Values.service.containerPort}}
  selector:
    app: {{.Release.Name}}
